### ISSUE TITLE
Unknown option --message-queue-host

### ISSUE THREAD

**Issue by chmandrade** [deepsense-io/seahorse-workflow-executor#1]
I am trying to test a simple workflow and I am getting this:
/spark-1.4.0-bin-hadoop2.3/bin/spark-submit --class io.deepsense.workflowexecutor.WorkflowExecutorApp ./workflowexecutor/target/scala-2.10/workflowexecutor.jar  --workflow-filename tefd.json --output-directory output --report-level medium --upload-report --message-queue-host 127.0.0.1

Error: Unknown option --message-queue-host
Error: Unknown argument '127.0.0.1'
Error: --message-queue-host is required
Try --help for more information.

**Comment by janek4mg** [comment]
Hi,

Please use the code from v0.5.0 tag, as this is the latest stable version.

Thanks!

**Comment by chmandrade** [comment]
I was having some problems on building the 0.5.0 tag but now I was able to generate the package.

Thanks,
Henrique
